### ISSUE TITLE
Whitelisting:

### ISSUE THREAD

**Issue by w1lla** [micm0/pyplanet_whitelist#1]
Hi,

You can already do whitelisting of players through the command in pyplanet already.

You just need to make a guestlist.txt in UserData\Config and enter the following in it:

`<?xml version="1.0" encoding="utf-8" ?>
<guestlist>
	<player>
		<login></login>
	</player>
</guestlist>`

**Comment by micm0** [comment]
Hey,

Thanks you for your comment.

The guestlist and the whitelist are 2 differents things.

- The guestlist feature is designed to allow a player to join the server if the slots are full and without typing the password.

- On the other hand, this whitelist PyPlanet app allows you to create a list of players who are authorized to join the server and prevent players not present in this list from joining the server even if they have the password. Which is useful for competitions like TTC, Sportyx, etc.
